api_base: "http://localhost:1234/v1"
api_key: "CHANGEME"
model: hermes-2-pro-mistral-7b"
context_max_tokens: 8192
assistant_minimum_context_tokens: 2048
stop_words: ["<|im_end|>\\n<|im_start|>", "<|im_start|>\n"]
session_db_url: "/Users/tg/Projects/awful_aj/test.db"
