//! # Database Schema Definitions
//!
//! **Auto-generated by Diesel CLI** - Do not edit manually.
//!
//! This module contains the table schema definitions for Awful Jade's SQLite database.
//! The schemas are generated by running `diesel print-schema` and define the structure
//! for all database tables used by the application.
//!
//! ## Tables
//!
//! ### `conversations`
//!
//! Stores named chat sessions:
//!
//! | Column | Type | Description |
//! |--------|------|-------------|
//! | `id` | Integer (PK) | Auto-increment primary key |
//! | `session_name` | Text | Human-readable session identifier |
//!
//! ### `messages`
//!
//! Stores individual conversation turns:
//!
//! | Column | Type | Description |
//! |--------|------|-------------|
//! | `id` | Integer (PK) | Auto-increment primary key |
//! | `role` | Text | Message sender: "system", "user", or "assistant" |
//! | `content` | Text | Raw message text |
//! | `dynamic` | Bool | True if generated at runtime, false if static |
//! | `conversation_id` | Integer? (FK) | Foreign key to `conversations` |
//!
//! ### `awful_configs`
//!
//! Stores configuration snapshots linked to conversations:
//!
//! | Column | Type | Description |
//! |--------|------|-------------|
//! | `id` | Integer (PK) | Auto-increment primary key |
//! | `api_base` | Text | OpenAI-compatible API endpoint URL |
//! | `api_key` | Text | API authentication key |
//! | `model` | Text | Model identifier |
//! | `context_max_tokens` | Integer | Maximum context window size |
//! | `assistant_minimum_context_tokens` | Integer | Reserved tokens for response |
//! | `stop_words` | Text | Comma-separated termination sequences |
//! | `conversation_id` | Integer? (FK) | Foreign key to `conversations` |
//!
//! ## Relationships
//!
//! ```text
//! conversations (1)
//!     ├── (*) messages
//!     └── (*) awful_configs
//! ```
//!
//! ## Regenerating This File
//!
//! To update the schema after database migrations:
//!
//! ```bash
//! diesel print-schema > src/schema.rs
//! ```
//!
//! **Warning**: Manual edits will be overwritten when regenerating.
//!
//! ## Usage
//!
//! These schema definitions are used by Diesel ORM for type-safe queries:
//!
//! ```rust,ignore
//! use crate::schema::{conversations, messages};
//! use diesel::prelude::*;
//!
//! // Query example
//! let all_conversations = conversations::table
//!     .load::<Conversation>(&mut conn)?;
//! ```
//!
//! ## See Also
//!
//! - [`crate::models`] - ORM models that map to these tables
//! - [Diesel Documentation](https://diesel.rs) - ORM framework documentation

// @generated automatically by Diesel CLI.

diesel::table! {
    awful_configs (id) {
        id -> Integer,
        api_base -> Text,
        api_key -> Text,
        model -> Text,
        context_max_tokens -> Integer,
        assistant_minimum_context_tokens -> Integer,
        stop_words -> Text,
        conversation_id -> Nullable<Integer>,
    }
}

diesel::table! {
    conversations (id) {
        id -> Integer,
        session_name -> Text,
    }
}

diesel::table! {
    messages (id) {
        id -> Integer,
        role -> Text,
        content -> Text,
        dynamic -> Bool,
        conversation_id -> Nullable<Integer>,
    }
}

diesel::joinable!(awful_configs -> conversations (conversation_id));
diesel::joinable!(messages -> conversations (conversation_id));

diesel::allow_tables_to_appear_in_same_query!(
    awful_configs,
    conversations,
    messages,
);
